"""Provider abstraction layer for LLM interactions and tool calling.

Isolates provider-specific SDK details from the core agent execution loop.
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, Field

from agent.tools.base import BaseTool


class ToolCall(BaseModel):
    """Normalized representation of a model-requested tool invocation."""
    call_id: str = Field(description="Unique correlation ID for tool call")
    tool_name: str = Field(description="Name of tool to invoke")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Parsed argument parameters")


class LLMMessage(BaseModel):
    """Normalized chat message passed to an LLM provider."""
    role: str = Field(description="'system', 'user', 'assistant', or 'tool'")
    content: str | None = Field(default=None, description="Observable text content")
    tool_calls: list[ToolCall] | None = Field(default=None, description="Tool calls generated by assistant")
    tool_call_id: str | None = Field(default=None, description="Referenced call_id for tool results")
    name: str | None = Field(default=None, description="Tool name for tool role")


class LLMResponse(BaseModel):
    """Structured response returned by an LLM provider."""
    content: str | None = Field(default=None, description="Observable response text")
    tool_calls: list[ToolCall] = Field(default_factory=list, description="Requested tool calls")
    finish_reason: str | None = Field(default="stop", description="Model termination reason")
    model: str | None = Field(default="unknown", description="Model name")


class LLMProvider(ABC):
    """Abstract interface for LLM providers supporting function/tool calling."""

    @abstractmethod
    def generate(
        self,
        messages: list[LLMMessage],
        tools: list[BaseTool] | None = None,
    ) -> LLMResponse:
        """Send conversation history and tool definitions to the LLM and receive a structured response."""

    @staticmethod
    def create_user_message(content: str) -> LLMMessage:
        return LLMMessage(role="user", content=content)

    @staticmethod
    def create_system_message(content: str) -> LLMMessage:
        return LLMMessage(role="system", content=content)

    @staticmethod
    def create_tool_result_message(tool_call_id: str, tool_name: str, result: Any) -> LLMMessage:
        content_str = json.dumps(result) if not isinstance(result, str) else result
        return LLMMessage(
            role="tool",
            tool_call_id=tool_call_id,
            name=tool_name,
            content=content_str,
        )


class MockLLMProvider(LLMProvider):
    """Deterministic Mock LLM Provider for offline testing and verification.

    Simulates multi-turn tool calling flows when live credentials are not available.
    """

    def __init__(self, canned_responses: list[LLMResponse] | None = None) -> None:
        self.canned_responses = list(canned_responses) if canned_responses else []
        self._call_count = 0

    def generate(
        self,
        messages: list[LLMMessage],
        tools: list[BaseTool] | None = None,
    ) -> LLMResponse:
        # If explicit canned responses are provided, yield them sequentially
        if self.canned_responses:
            if self._call_count < len(self.canned_responses):
                resp = self.canned_responses[self._call_count]
                self._call_count += 1
                return resp
            return LLMResponse(
                content="Task completed successfully.",
                tool_calls=[],
                finish_reason="stop",
                model="mock-llm-v1",
            )

        # Inspect conversation state to simulate realistic task flow
        messages[-1] if messages else None
        all_tool_messages = [m for m in messages if m.role == "tool"]

        # Case 1: Customer refund flow
        if any("ORD-" in (m.content or "") for m in messages if m.role == "user"):
            # Extract order ID from user message if possible
            order_id = "ORD-1001"
            for m in messages:
                if m.role == "user" and m.content and "ORD-" in m.content:
                    for token in m.content.split():
                        clean = token.strip(".,;:!?\"'")
                        if clean.startswith("ORD-"):
                            order_id = clean
                            break

            # Turn 1: Lookup order first
            if not any(m.name == "order_lookup" for m in all_tool_messages):
                return LLMResponse(
                    content=f"Checking order details for {order_id}.",
                    tool_calls=[
                        ToolCall(
                            call_id="call_mock_lookup_1",
                            tool_name="order_lookup",
                            arguments={"order_id": order_id},
                        )
                    ],
                    finish_reason="tool_calls",
                    model="mock-llm-v1",
                )

            # Turn 2: Order lookup succeeded, execute refund
            lookup_result_str = next(m.content for m in all_tool_messages if m.name == "order_lookup")
            lookup_data = json.loads(lookup_result_str) if lookup_result_str else {}

            if not any(m.name == "refund_tool" for m in all_tool_messages):
                if lookup_data.get("refund_eligible"):
                    amount = lookup_data.get("refundable_amount", 120.00)
                    return LLMResponse(
                        content=f"Order {order_id} is delivered and eligible. Initiating refund for ${amount:.2f}.",
                        tool_calls=[
                            ToolCall(
                                call_id="call_mock_refund_2",
                                tool_name="refund_tool",
                                arguments={"order_id": order_id, "amount": amount},
                            )
                        ],
                        finish_reason="tool_calls",
                        model="mock-llm-v1",
                    )
                else:
                    status = lookup_data.get("status", "UNKNOWN")
                    return LLMResponse(
                        content=(
                            f"Order {order_id} has status {status} and is currently ineligible for a refund. "
                            "Refunds can only be processed after delivery."
                        ),
                        tool_calls=[],
                        finish_reason="stop",
                        model="mock-llm-v1",
                    )

            # Turn 3: Refund executed, return final answer
            refund_result_str = next(m.content for m in all_tool_messages if m.name == "refund_tool")
            refund_data = json.loads(refund_result_str) if refund_result_str else {}
            tx_id = refund_data.get("transaction_id", "synth-tx-demo")
            amount = refund_data.get("refunded_amount", 120.00)

            return LLMResponse(
                content=(
                    f"A refund of ${amount:.2f} for order {order_id} has been processed successfully. "
                    f"Transaction ID: {tx_id}."
                ),
                tool_calls=[],
                finish_reason="stop",
                model="mock-llm-v1",
            )

        # Case 2: Research summary flow
        if any("search" in (m.content or "").lower() or "research" in (m.content or "").lower() for m in messages if m.role == "user"):
            if not any(m.name == "web_search" for m in all_tool_messages):
                return LLMResponse(
                    content="Searching synthetic research corpus for relevant governance standards.",
                    tool_calls=[
                        ToolCall(
                            call_id="call_mock_search_1",
                            tool_name="web_search",
                            arguments={"query": "AI agent governance observability audit", "max_results": 2},
                        )
                    ],
                    finish_reason="tool_calls",
                    model="mock-llm-v1",
                )
            else:
                return LLMResponse(
                    content=(
                        "According to synthetic documentation in public_web_stub, AI agent governance "
                        "requires post-hoc audit trails verifying tool scope boundaries, PII redaction, "
                        "and factual groundedness."
                    ),
                    tool_calls=[],
                    finish_reason="stop",
                    model="mock-llm-v1",
                )

        # Generic default response
        return LLMResponse(
            content="Task completed based on provided instructions.",
            tool_calls=[],
            finish_reason="stop",
            model="mock-llm-v1",
        )
